using Microsoft.EntityFrameworkCore;
using Challenge.Core.Models;
using System;
using System.Collections.Generic;

namespace Challenge.Infrastructure.DataAccess
{
    public class ChallengeContext : DbContext
    {
        public ChallengeContext(DbContextOptions<ChallengeContext> options) : base(options)
        {
        }

        public DbSet<User> Users { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Link> Links { get; set; }
        public DbSet<WebPage> WebPages { get; set; }
        public DbSet<Stopword> Stopwords { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            ConfigureForUser(modelBuilder);
            ConfigureForRole(modelBuilder);
            ConfigureForUserRole(modelBuilder);
            ConfigureForWebPage(modelBuilder);
            ConfigureForLink(modelBuilder);
            ConfigureForTag(modelBuilder);
            ConfigureForKeyword(modelBuilder);
            ConfigureForStopword(modelBuilder);
            SeedData(modelBuilder);
        }

        private void ConfigureForUser(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>().ToTable("users");
            modelBuilder.Entity<User>().HasKey(x => x.Id);
            modelBuilder.Entity<User>().HasAlternateKey(x => x.Email);
            modelBuilder.Entity<User>().Property(x => x.Email).IsRequired().HasMaxLength(255);
            modelBuilder.Entity<User>().HasIndex(x => x.Email).IsUnique();
            modelBuilder.Entity<User>().Property(x => x.DisplayName).IsRequired().HasMaxLength(255);
            modelBuilder.Entity<User>().Property(x => x.PasswordHash).HasMaxLength(255).IsRequired();
            modelBuilder.Entity<User>().Ignore(x => x.Roles);
        }

        private void ConfigureForRole(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Role>().ToTable("roles");
            modelBuilder.Entity<Role>().HasKey(x => x.Name);
            modelBuilder.Entity<Role>().Property(x => x.Name).HasMaxLength(200);
            modelBuilder.Entity<Role>().Property(x => x.DisplayName).HasMaxLength(500);
        }

        private void ConfigureForUserRole(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UserRole>().ToTable("user_roles");
            modelBuilder.Entity<UserRole>().HasKey(x => new { x.UserId, x.RoleName });
            modelBuilder.Entity<UserRole>().HasOne(x => x.User).WithMany(x => x.UserRoles).HasForeignKey(x => x.UserId).IsRequired();
            modelBuilder.Entity<UserRole>().HasOne(x => x.Role).WithMany().HasForeignKey(x => x.RoleName).IsRequired();
        }

        private void ConfigureForWebPage(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<WebPage>().ToTable("webpages");
            modelBuilder.Entity<WebPage>().HasKey(x => x.Url);
        }

        private void ConfigureForLink(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Link>().ToTable("links");
            modelBuilder.Entity<Link>().HasKey(x => new { x.WebPageUrl, x.UserId });
            modelBuilder.Entity<Link>().HasOne(x => x.WebPage).WithMany().HasForeignKey(x => x.WebPageUrl).IsRequired();
            modelBuilder.Entity<Link>().HasOne(x => x.User).WithMany(x => x.Links).HasForeignKey(x => x.UserId).IsRequired();
        }
        private void ConfigureForTag(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<Tag>().ToTable("tags");
            modelBuilder.Entity<Tag>().HasKey(x => new { x.Content, x.Url, x.LinkUserId });
            modelBuilder.Entity<Tag>().HasOne(x => x.Link).WithMany(x => x.Tags).HasForeignKey(x => new { x.Url, x.LinkUserId }).IsRequired();
        }

        private void ConfigureForKeyword(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<Keyword>().ToTable("keywords");
            modelBuilder.Entity<Keyword>().HasKey(x => new { x.Word, x.WebPageUrl });
            modelBuilder.Entity<Keyword>().HasOne(x => x.WebPage).WithMany(x => x.Keywords).HasForeignKey(x => x.WebPageUrl).IsRequired();
        }

        private void ConfigureForStopword(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Stopword>().ToTable("stopwords");
            modelBuilder.Entity<Stopword>().HasKey(x => x.Word);
        }

        private void SeedData(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Role>().HasData(new Role("Admin"));
            modelBuilder.Entity<Role>().HasData(new Role("User"));

            List<Stopword> stopwords = new List<Stopword> {
                new Stopword("a"),
                new Stopword("about"),
                new Stopword("above"),
                new Stopword("after"),
                new Stopword("again"),
                new Stopword("against"),
                new Stopword("ain"),
                new Stopword("all"),
                new Stopword("am"),
                new Stopword("an"),
                new Stopword("and"),
                new Stopword("any"),
                new Stopword("are"),
                new Stopword("aren"),
                new Stopword("aren't"),
                new Stopword("as"),
                new Stopword("at"),
                new Stopword("be"),
                new Stopword("because"),
                new Stopword("been"),
                new Stopword("before"),
                new Stopword("being"),
                new Stopword("below"),
                new Stopword("between"),
                new Stopword("both"),
                new Stopword("but"),
                new Stopword("by"),
                new Stopword("can"),
                new Stopword("couldn"),
                new Stopword("couldn't"),
                new Stopword("d"),
                new Stopword("did"),
                new Stopword("didn"),
                new Stopword("didn't"),
                new Stopword("do"),
                new Stopword("does"),
                new Stopword("doesn"),
                new Stopword("doesn't"),
                new Stopword("doing"),
                new Stopword("don"),
                new Stopword("don't"),
                new Stopword("down"),
                new Stopword("during"),
                new Stopword("each"),
                new Stopword("few"),
                new Stopword("for"),
                new Stopword("from"),
                new Stopword("further"),
                new Stopword("had"),
                new Stopword("hadn"),
                new Stopword("hadn't"),
                new Stopword("has"),
                new Stopword("hasn"),
                new Stopword("hasn't"),
                new Stopword("have"),
                new Stopword("haven"),
                new Stopword("haven't"),
                new Stopword("having"),
                new Stopword("he"),
                new Stopword("her"),
                new Stopword("here"),
                new Stopword("hers"),
                new Stopword("herself"),
                new Stopword("him"),
                new Stopword("himself"),
                new Stopword("his"),
                new Stopword("how"),
                new Stopword("i"),
                new Stopword("if"),
                new Stopword("in"),
                new Stopword("into"),
                new Stopword("is"),
                new Stopword("isn"),
                new Stopword("isn't"),
                new Stopword("it"),
                new Stopword("it's"),
                new Stopword("its"),
                new Stopword("itself"),
                new Stopword("just"),
                new Stopword("ll"),
                new Stopword("m"),
                new Stopword("ma"),
                new Stopword("me"),
                new Stopword("mightn"),
                new Stopword("mightn't"),
                new Stopword("more"),
                new Stopword("most"),
                new Stopword("mustn"),
                new Stopword("mustn't"),
                new Stopword("my"),
                new Stopword("myself"),
                new Stopword("needn"),
                new Stopword("needn't"),
                new Stopword("no"),
                new Stopword("nor"),
                new Stopword("not"),
                new Stopword("now"),
                new Stopword("o"),
                new Stopword("of"),
                new Stopword("off"),
                new Stopword("on"),
                new Stopword("once"),
                new Stopword("only"),
                new Stopword("or"),
                new Stopword("other"),
                new Stopword("our"),
                new Stopword("ours"),
                new Stopword("ourselves"),
                new Stopword("out"),
                new Stopword("over"),
                new Stopword("own"),
                new Stopword("re"),
                new Stopword("s"),
                new Stopword("same"),
                new Stopword("shan"),
                new Stopword("shan't"),
                new Stopword("she"),
                new Stopword("she's"),
                new Stopword("should"),
                new Stopword("should've"),
                new Stopword("shouldn"),
                new Stopword("shouldn't"),
                new Stopword("so"),
                new Stopword("some"),
                new Stopword("such"),
                new Stopword("t"),
                new Stopword("than"),
                new Stopword("that"),
                new Stopword("that'll"),
                new Stopword("the"),
                new Stopword("their"),
                new Stopword("theirs"),
                new Stopword("them"),
                new Stopword("themselves"),
                new Stopword("then"),
                new Stopword("there"),
                new Stopword("these"),
                new Stopword("they"),
                new Stopword("this"),
                new Stopword("those"),
                new Stopword("through"),
                new Stopword("to"),
                new Stopword("too"),
                new Stopword("under"),
                new Stopword("until"),
                new Stopword("up"),
                new Stopword("ve"),
                new Stopword("very"),
                new Stopword("was"),
                new Stopword("wasn"),
                new Stopword("wasn't"),
                new Stopword("we"),
                new Stopword("were"),
                new Stopword("weren"),
                new Stopword("weren't"),
                new Stopword("what"),
                new Stopword("when"),
                new Stopword("where"),
                new Stopword("which"),
                new Stopword("while"),
                new Stopword("who"),
                new Stopword("whom"),
                new Stopword("why"),
                new Stopword("will"),
                new Stopword("with"),
                new Stopword("won"),
                new Stopword("won't"),
                new Stopword("wouldn"),
                new Stopword("wouldn't"),
                new Stopword("y"),
                new Stopword("you"),
                new Stopword("you'd"),
                new Stopword("you'll"),
                new Stopword("you're"),
                new Stopword("you've"),
                new Stopword("your"),
                new Stopword("yours"),
                new Stopword("yourself"),
                new Stopword("yourselves"),
                new Stopword("could"),
                new Stopword("he'd"),
                new Stopword("he'll"),
                new Stopword("he's"),
                new Stopword("here's"),
                new Stopword("how's"),
                new Stopword("i'd"),
                new Stopword("i'll"),
                new Stopword("i'm"),
                new Stopword("i've"),
                new Stopword("let's"),
                new Stopword("ought"),
                new Stopword("she'd"),
                new Stopword("she'll"),
                new Stopword("that's"),
                new Stopword("there's"),
                new Stopword("they'd"),
                new Stopword("they'll"),
                new Stopword("they're"),
                new Stopword("they've"),
                new Stopword("we'd"),
                new Stopword("we'll"),
                new Stopword("we're"),
                new Stopword("we've"),
                new Stopword("what's"),
                new Stopword("when's"),
                new Stopword("where's"),
                new Stopword("who's"),
                new Stopword("why's"),
                new Stopword("would"),
                new Stopword("able"),
                new Stopword("abst"),
                new Stopword("accordance"),
                new Stopword("according"),
                new Stopword("accordingly"),
                new Stopword("across"),
                new Stopword("act"),
                new Stopword("actually"),
                new Stopword("added"),
                new Stopword("adj"),
                new Stopword("affected"),
                new Stopword("affecting"),
                new Stopword("affects"),
                new Stopword("afterwards"),
                new Stopword("ah"),
                new Stopword("almost"),
                new Stopword("alone"),
                new Stopword("along"),
                new Stopword("already"),
                new Stopword("also"),
                new Stopword("although"),
                new Stopword("always"),
                new Stopword("among"),
                new Stopword("amongst"),
                new Stopword("announce"),
                new Stopword("another"),
                new Stopword("anybody"),
                new Stopword("anyhow"),
                new Stopword("anymore"),
                new Stopword("anyone"),
                new Stopword("anything"),
                new Stopword("anyway"),
                new Stopword("anyways"),
                new Stopword("anywhere"),
                new Stopword("apparently"),
                new Stopword("approximately"),
                new Stopword("arent"),
                new Stopword("arise"),
                new Stopword("around"),
                new Stopword("aside"),
                new Stopword("ask"),
                new Stopword("asking"),
                new Stopword("auth"),
                new Stopword("available"),
                new Stopword("away"),
                new Stopword("awfully"),
                new Stopword("b"),
                new Stopword("back"),
                new Stopword("became"),
                new Stopword("become"),
                new Stopword("becomes"),
                new Stopword("becoming"),
                new Stopword("beforehand"),
                new Stopword("begin"),
                new Stopword("beginning"),
                new Stopword("beginnings"),
                new Stopword("begins"),
                new Stopword("behind"),
                new Stopword("believe"),
                new Stopword("beside"),
                new Stopword("besides"),
                new Stopword("beyond"),
                new Stopword("biol"),
                new Stopword("brief"),
                new Stopword("briefly"),
                new Stopword("c"),
                new Stopword("ca"),
                new Stopword("came"),
                new Stopword("cannot"),
                new Stopword("can't"),
                new Stopword("cause"),
                new Stopword("causes"),
                new Stopword("certain"),
                new Stopword("certainly"),
                new Stopword("co"),
                new Stopword("com"),
                new Stopword("come"),
                new Stopword("comes"),
                new Stopword("contain"),
                new Stopword("containing"),
                new Stopword("contains"),
                new Stopword("couldnt"),
                new Stopword("date"),
                new Stopword("different"),
                new Stopword("done"),
                new Stopword("downwards"),
                new Stopword("due"),
                new Stopword("e"),
                new Stopword("ed"),
                new Stopword("edu"),
                new Stopword("effect"),
                new Stopword("eg"),
                new Stopword("eight"),
                new Stopword("eighty"),
                new Stopword("either"),
                new Stopword("else"),
                new Stopword("elsewhere"),
                new Stopword("end"),
                new Stopword("ending"),
                new Stopword("enough"),
                new Stopword("especially"),
                new Stopword("et"),
                new Stopword("etc"),
                new Stopword("even"),
                new Stopword("ever"),
                new Stopword("every"),
                new Stopword("everybody"),
                new Stopword("everyone"),
                new Stopword("everything"),
                new Stopword("everywhere"),
                new Stopword("ex"),
                new Stopword("except"),
                new Stopword("f"),
                new Stopword("far"),
                new Stopword("ff"),
                new Stopword("fifth"),
                new Stopword("first"),
                new Stopword("five"),
                new Stopword("fix"),
                new Stopword("followed"),
                new Stopword("following"),
                new Stopword("follows"),
                new Stopword("former"),
                new Stopword("formerly"),
                new Stopword("forth"),
                new Stopword("found"),
                new Stopword("four"),
                new Stopword("furthermore"),
                new Stopword("g"),
                new Stopword("gave"),
                new Stopword("get"),
                new Stopword("gets"),
                new Stopword("getting"),
                new Stopword("give"),
                new Stopword("given"),
                new Stopword("gives"),
                new Stopword("giving"),
                new Stopword("go"),
                new Stopword("goes"),
                new Stopword("gone"),
                new Stopword("got"),
                new Stopword("gotten"),
                new Stopword("h"),
                new Stopword("happens"),
                new Stopword("hardly"),
                new Stopword("hed"),
                new Stopword("hence"),
                new Stopword("hereafter"),
                new Stopword("hereby"),
                new Stopword("herein"),
                new Stopword("heres"),
                new Stopword("hereupon"),
                new Stopword("hes"),
                new Stopword("hi"),
                new Stopword("hid"),
                new Stopword("hither"),
                new Stopword("home"),
                new Stopword("howbeit"),
                new Stopword("however"),
                new Stopword("hundred"),
                new Stopword("id"),
                new Stopword("ie"),
                new Stopword("im"),
                new Stopword("immediate"),
                new Stopword("immediately"),
                new Stopword("importance"),
                new Stopword("important"),
                new Stopword("inc"),
                new Stopword("indeed"),
                new Stopword("index"),
                new Stopword("information"),
                new Stopword("instead"),
                new Stopword("invention"),
                new Stopword("inward"),
                new Stopword("itd"),
                new Stopword("it'll"),
                new Stopword("j"),
                new Stopword("k"),
                new Stopword("keep"),
                new Stopword("keeps"),
                new Stopword("kept"),
                new Stopword("kg"),
                new Stopword("km"),
                new Stopword("know"),
                new Stopword("known"),
                new Stopword("knows"),
                new Stopword("l"),
                new Stopword("largely"),
                new Stopword("last"),
                new Stopword("lately"),
                new Stopword("later"),
                new Stopword("latter"),
                new Stopword("latterly"),
                new Stopword("least"),
                new Stopword("less"),
                new Stopword("lest"),
                new Stopword("let"),
                new Stopword("lets"),
                new Stopword("like"),
                new Stopword("liked"),
                new Stopword("likely"),
                new Stopword("line"),
                new Stopword("little"),
                new Stopword("'ll"),
                new Stopword("look"),
                new Stopword("looking"),
                new Stopword("looks"),
                new Stopword("ltd"),
                new Stopword("made"),
                new Stopword("mainly"),
                new Stopword("make"),
                new Stopword("makes"),
                new Stopword("many"),
                new Stopword("may"),
                new Stopword("maybe"),
                new Stopword("mean"),
                new Stopword("means"),
                new Stopword("meantime"),
                new Stopword("meanwhile"),
                new Stopword("merely"),
                new Stopword("mg"),
                new Stopword("might"),
                new Stopword("million"),
                new Stopword("miss"),
                new Stopword("ml"),
                new Stopword("moreover"),
                new Stopword("mostly"),
                new Stopword("mr"),
                new Stopword("mrs"),
                new Stopword("much"),
                new Stopword("mug"),
                new Stopword("must"),
                new Stopword("n"),
                new Stopword("na"),
                new Stopword("name"),
                new Stopword("namely"),
                new Stopword("nay"),
                new Stopword("nd"),
                new Stopword("near"),
                new Stopword("nearly"),
                new Stopword("necessarily"),
                new Stopword("necessary"),
                new Stopword("need"),
                new Stopword("needs"),
                new Stopword("neither"),
                new Stopword("never"),
                new Stopword("nevertheless"),
                new Stopword("new"),
                new Stopword("next"),
                new Stopword("nine"),
                new Stopword("ninety"),
                new Stopword("nobody"),
                new Stopword("non"),
                new Stopword("none"),
                new Stopword("nonetheless"),
                new Stopword("noone"),
                new Stopword("normally"),
                new Stopword("nos"),
                new Stopword("noted"),
                new Stopword("nothing"),
                new Stopword("nowhere"),
                new Stopword("obtain"),
                new Stopword("obtained"),
                new Stopword("obviously"),
                new Stopword("often"),
                new Stopword("oh"),
                new Stopword("ok"),
                new Stopword("okay"),
                new Stopword("old"),
                new Stopword("omitted"),
                new Stopword("one"),
                new Stopword("ones"),
                new Stopword("onto"),
                new Stopword("ord"),
                new Stopword("others"),
                new Stopword("otherwise"),
                new Stopword("outside"),
                new Stopword("overall"),
                new Stopword("owing"),
                new Stopword("p"),
                new Stopword("page"),
                new Stopword("pages"),
                new Stopword("part"),
                new Stopword("particular"),
                new Stopword("particularly"),
                new Stopword("past"),
                new Stopword("per"),
                new Stopword("perhaps"),
                new Stopword("placed"),
                new Stopword("please"),
                new Stopword("plus"),
                new Stopword("poorly"),
                new Stopword("possible"),
                new Stopword("possibly"),
                new Stopword("potentially"),
                new Stopword("pp"),
                new Stopword("predominantly"),
                new Stopword("present"),
                new Stopword("previously"),
                new Stopword("primarily"),
                new Stopword("probably"),
                new Stopword("promptly"),
                new Stopword("proud"),
                new Stopword("provides"),
                new Stopword("put"),
                new Stopword("q"),
                new Stopword("que"),
                new Stopword("quickly"),
                new Stopword("quite"),
                new Stopword("qv"),
                new Stopword("r"),
                new Stopword("ran"),
                new Stopword("rather"),
                new Stopword("rd"),
                new Stopword("readily"),
                new Stopword("really"),
                new Stopword("recent"),
                new Stopword("recently"),
                new Stopword("ref"),
                new Stopword("refs"),
                new Stopword("regarding"),
                new Stopword("regardless"),
                new Stopword("regards"),
                new Stopword("related"),
                new Stopword("relatively"),
                new Stopword("research"),
                new Stopword("respectively"),
                new Stopword("resulted"),
                new Stopword("resulting"),
                new Stopword("results"),
                new Stopword("right"),
                new Stopword("run"),
                new Stopword("said"),
                new Stopword("saw"),
                new Stopword("say"),
                new Stopword("saying"),
                new Stopword("says"),
                new Stopword("sec"),
                new Stopword("section"),
                new Stopword("see"),
                new Stopword("seeing"),
                new Stopword("seem"),
                new Stopword("seemed"),
                new Stopword("seeming"),
                new Stopword("seems"),
                new Stopword("seen"),
                new Stopword("self"),
                new Stopword("selves"),
                new Stopword("sent"),
                new Stopword("seven"),
                new Stopword("several"),
                new Stopword("shall"),
                new Stopword("shed"),
                new Stopword("shes"),
                new Stopword("show"),
                new Stopword("showed"),
                new Stopword("shown"),
                new Stopword("showns"),
                new Stopword("shows"),
                new Stopword("significant"),
                new Stopword("significantly"),
                new Stopword("similar"),
                new Stopword("similarly"),
                new Stopword("since"),
                new Stopword("six"),
                new Stopword("slightly"),
                new Stopword("somebody"),
                new Stopword("somehow"),
                new Stopword("someone"),
                new Stopword("somethan"),
                new Stopword("something"),
                new Stopword("sometime"),
                new Stopword("sometimes"),
                new Stopword("somewhat"),
                new Stopword("somewhere"),
                new Stopword("soon"),
                new Stopword("sorry"),
                new Stopword("specifically"),
                new Stopword("specified"),
                new Stopword("specify"),
                new Stopword("specifying"),
                new Stopword("still"),
                new Stopword("stop"),
                new Stopword("strongly"),
                new Stopword("sub"),
                new Stopword("substantially"),
                new Stopword("successfully"),
                new Stopword("sufficiently"),
                new Stopword("suggest"),
                new Stopword("sup"),
                new Stopword("sure"),
                new Stopword("take"),
                new Stopword("taken"),
                new Stopword("taking"),
                new Stopword("tell"),
                new Stopword("tends"),
                new Stopword("th"),
                new Stopword("thank"),
                new Stopword("thanks"),
                new Stopword("thanx"),
                new Stopword("thats"),
                new Stopword("that've"),
                new Stopword("thence"),
                new Stopword("thereafter"),
                new Stopword("thereby"),
                new Stopword("thered"),
                new Stopword("therefore"),
                new Stopword("therein"),
                new Stopword("there'll"),
                new Stopword("thereof"),
                new Stopword("therere"),
                new Stopword("theres"),
                new Stopword("thereto"),
                new Stopword("thereupon"),
                new Stopword("there've"),
                new Stopword("theyd"),
                new Stopword("theyre"),
                new Stopword("think"),
                new Stopword("thou"),
                new Stopword("though"),
                new Stopword("thoughh"),
                new Stopword("thousand"),
                new Stopword("throug"),
                new Stopword("throughout"),
                new Stopword("thru"),
                new Stopword("thus"),
                new Stopword("til"),
                new Stopword("tip"),
                new Stopword("together"),
                new Stopword("took"),
                new Stopword("toward"),
                new Stopword("towards"),
                new Stopword("tried"),
                new Stopword("tries"),
                new Stopword("truly"),
                new Stopword("try"),
                new Stopword("trying"),
                new Stopword("ts"),
                new Stopword("twice"),
                new Stopword("two"),
                new Stopword("u"),
                new Stopword("un"),
                new Stopword("unfortunately"),
                new Stopword("unless"),
                new Stopword("unlike"),
                new Stopword("unlikely"),
                new Stopword("unto"),
                new Stopword("upon"),
                new Stopword("ups"),
                new Stopword("us"),
                new Stopword("use"),
                new Stopword("used"),
                new Stopword("useful"),
                new Stopword("usefully"),
                new Stopword("usefulness"),
                new Stopword("uses"),
                new Stopword("using"),
                new Stopword("usually"),
                new Stopword("v"),
                new Stopword("value"),
                new Stopword("various"),
                new Stopword("'ve"),
                new Stopword("via"),
                new Stopword("viz"),
                new Stopword("vol"),
                new Stopword("vols"),
                new Stopword("vs"),
                new Stopword("w"),
                new Stopword("want"),
                new Stopword("wants"),
                new Stopword("wasnt"),
                new Stopword("way"),
                new Stopword("wed"),
                new Stopword("welcome"),
                new Stopword("went"),
                new Stopword("werent"),
                new Stopword("whatever"),
                new Stopword("what'll"),
                new Stopword("whats"),
                new Stopword("whence"),
                new Stopword("whenever"),
                new Stopword("whereafter"),
                new Stopword("whereas"),
                new Stopword("whereby"),
                new Stopword("wherein"),
                new Stopword("wheres"),
                new Stopword("whereupon"),
                new Stopword("wherever"),
                new Stopword("whether"),
                new Stopword("whim"),
                new Stopword("whither"),
                new Stopword("whod"),
                new Stopword("whoever"),
                new Stopword("whole"),
                new Stopword("who'll"),
                new Stopword("whomever"),
                new Stopword("whos"),
                new Stopword("whose"),
                new Stopword("widely"),
                new Stopword("willing"),
                new Stopword("wish"),
                new Stopword("within"),
                new Stopword("without"),
                new Stopword("wont"),
                new Stopword("words"),
                new Stopword("world"),
                new Stopword("wouldnt"),
                new Stopword("www"),
                new Stopword("x"),
                new Stopword("yes"),
                new Stopword("yet"),
                new Stopword("youd"),
                new Stopword("youre"),
                new Stopword("z"),
                new Stopword("zero"),
                new Stopword("a's"),
                new Stopword("ain't"),
                new Stopword("allow"),
                new Stopword("allows"),
                new Stopword("apart"),
                new Stopword("appear"),
                new Stopword("appreciate"),
                new Stopword("appropriate"),
                new Stopword("associated"),
                new Stopword("best"),
                new Stopword("better"),
                new Stopword("c'mon"),
                new Stopword("c's"),
                new Stopword("cant"),
                new Stopword("changes"),
                new Stopword("clearly"),
                new Stopword("concerning"),
                new Stopword("consequently"),
                new Stopword("consider"),
                new Stopword("considering"),
                new Stopword("corresponding"),
                new Stopword("course"),
                new Stopword("currently"),
                new Stopword("definitely"),
                new Stopword("described"),
                new Stopword("despite"),
                new Stopword("entirely"),
                new Stopword("exactly"),
                new Stopword("example"),
                new Stopword("going"),
                new Stopword("greetings"),
                new Stopword("hello"),
                new Stopword("help"),
                new Stopword("hopefully"),
                new Stopword("ignored"),
                new Stopword("inasmuch"),
                new Stopword("indicate"),
                new Stopword("indicated"),
                new Stopword("indicates"),
                new Stopword("inner"),
                new Stopword("insofar"),
                new Stopword("it'd"),
                new Stopword("novel"),
                new Stopword("presumably"),
                new Stopword("reasonably"),
                new Stopword("second"),
                new Stopword("secondly"),
                new Stopword("sensible"),
                new Stopword("serious"),
                new Stopword("seriously"),
                new Stopword("t's"),
                new Stopword("third"),
                new Stopword("thorough"),
                new Stopword("thoroughly"),
                new Stopword("three"),
                new Stopword("well"),
                new Stopword("wonder")
            };

            modelBuilder.Entity<Stopword>().HasData(stopwords);
        }
    }
}